<?php
$html = '
               <table cellpadding="0" cellspacing="1">
                        <tr>
                                <td align="center" width="50%" class="admin_menu"><a href="'.getlink("&amp;file=albmgr").'">'.ALBMGR_LNK.'</a></td>
                                <td align="center" width="50%" class="admin_menu"><a href="'.getlink("&amp;file=modifyalb").'">'.MODIFYALB_LNK.'</a></td>
                        </tr>
                </table>';
?>
