<?php
$template_user_list_info_box = '<table cellspacing="1" cellpadding="0" border="0" width="100%" class="user_thumb_infobox">
                <tr class="user_thumb_infobox">
<td><a class="user_thumb_infobox" href="{USER_PROFILE_LINK}">{username}</a></td>
                </tr>
                <tr>
                        <td>{ALBUMS}</td>
                </tr>
                <tr>
                        <td>{PICTURES}</td>
                </tr>
        </table>';
?>
