<?php
$html = "
               <table cellpadding=\"0\" cellspacing=\"1\">
                        <tr>
                                <td class=\"admin_menu\"><a href=\"$CPG_URL&file=albmgr\">".ALBMGR_LNK."</a></td>
                                <td class=\"admin_menu\"><a href=\"$CPG_URL&file=modifyalb\">".MODIFYALB_LNK."</a></td>
                                <td class=\"admin_menu\"><a href=\"$CPG_URL&file=profile&op=edit_profile\">".MY_PROF_LNK."</a></td>
                        </tr>
                </table>";
?>
