/*
	@import "poodle"
*/

Poodle.Emoji = {

	// Set to true to use native browser emoji's
	use_native: false,

	// JavaScript strings are UTF-16
	// 1F300..1F3FF = \ud83c[\udf00-\udfff] = Miscellaneous Symbols and Pictographs
	// 1F400..1F5FF = \ud83d[\udc00-\uddff] = Miscellaneous Symbols and Pictographs
	// 1F600..1F64F = \ud83d[\ude00-\ude4f] = Emoticons
	// 1F650..1F67F = \ud83d[\ude50-\ud7ff] = Ornamental Dingbats
	// 1F680..1F6FF = \ud83d[\ude80-\udeff] = Transport and Map Symbols
	// 1F910..1F9C0 = \ud83e[\udd10-\uddc0] =
	regex: /\ud83c[\udf00-\udfff]|\ud83d[\udc00-\udeff]|\ud83e[\udd10-\uddc0]/g,

	// List of supported emoji's
	emojis: {
		'🌀':'Cyclone',
		'🌁':'Foggy',
		'🌂':'Closed umbrella',
		'🌃':'Night with stars',
		'🌄':'Sunrise over mountains',
		'🌅':'Sunrise',
		'🌆':'Cityscape at dusk',
		'🌇':'Sunset over buildings',
		'🌈':'Rainbow',
		'🌉':'Bridge at night',
		'🌊':'Water wave',
		'🌋':'Volcano',
		'🌌':'Milky way',
		'🌍':'Earth globe europe-africa',
		'🌎':'Earth globe americas',
		'🌏':'Earth globe asia-australia',
		'🌐':'Globe with meridians',
		'🌑':'New moon symbol',
		'🌒':'Waxing crescent moon symbol',
		'🌓':'First quarter moon symbol',
		'🌔':'Waxing gibbous moon symbol',
		'🌕':'Full moon symbol',
		'🌖':'Waning gibbous moon symbol',
		'🌗':'Last quarter moon symbol',
		'🌘':'Waning crescent moon symbol',
		'🌙':'Crescent moon',
		'🌚':'New moon with face',
		'🌛':'First quarter moon with face',
		'🌜':'Last quarter moon with face',
		'🌝':'Full moon with face',
		'🌞':'Sun with face',
		'🌟':'Glowing star',
		'🌠':'Shooting star',
		'🌡':'Thermometer',
		'🌤':'White sun with small cloud',
		'🌥':'White sun behind cloud',
		'🌦':'White sun behind cloud with rain',
		'🌧':'Cloud with rain',
		'🌨':'Cloud with snow',
		'🌩':'Cloud with lightning',
		'🌪':'Cloud with tornado',
		'🌫':'Fog',
		'🌬':'Wind blowing face',
		'🌭':'Hot dog',
		'🌮':'Taco',
		'🌯':'Burrito',
		'🌰':'Chestnut',
		'🌱':'Seedling',
		'🌲':'Evergreen tree',
		'🌳':'Deciduous tree',
		'🌴':'Palm tree',
		'🌵':'Cactus',
		'🌶':'Hot pepper',
		'🌷':'Tulip',
		'🌸':'Cherry blossom',
		'🌹':'Rose',
		'🌺':'Hibiscus',
		'🌻':'Sunflower',
		'🌼':'Blossom',
		'🌽':'Ear of maize',
		'🌾':'Ear of rice',
		'🌿':'Herb',
		'🍀':'Four leaf clover',
		'🍁':'Maple leaf',
		'🍂':'Fallen leaf',
		'🍃':'Leaf fluttering in wind',
		'🍄':'Mushroom',
		'🍅':'Tomato',
		'🍆':'Aubergine',
		'🍇':'Grapes',
		'🍈':'Melon',
		'🍉':'Watermelon',
		'🍊':'Tangerine',
		'🍋':'Lemon',
		'🍌':'Banana',
		'🍍':'Pineapple',
		'🍎':'Red apple',
		'🍏':'Green apple',
		'🍐':'Pear',
		'🍑':'Peach',
		'🍒':'Cherries',
		'🍓':'Strawberry',
		'🍔':'Hamburger',
		'🍕':'Slice of pizza',
		'🍖':'Meat on bone',
		'🍗':'Poultry leg',
		'🍘':'Rice cracker',
		'🍙':'Rice ball',
		'🍚':'Cooked rice',
		'🍛':'Curry and rice',
		'🍜':'Steaming bowl',
		'🍝':'Spaghetti',
		'🍞':'Bread',
		'🍟':'French fries',
		'🍠':'Roasted sweet potato',
		'🍡':'Dango',
		'🍢':'Oden',
		'🍣':'Sushi',
		'🍤':'Fried shrimp',
		'🍥':'Fish cake with swirl design',
		'🍦':'Soft ice cream',
		'🍧':'Shaved ice',
		'🍨':'Ice cream',
		'🍩':'Doughnut',
		'🍪':'Cookie',
		'🍫':'Chocolate bar',
		'🍬':'Candy',
		'🍭':'Lollipop',
		'🍮':'Custard',
		'🍯':'Honey pot',
		'🍰':'Shortcake',
		'🍱':'Bento box',
		'🍲':'Pot of food',
		'🍳':'Cooking',
		'🍴':'Fork and knife',
		'🍵':'Teacup without handle',
		'🍶':'Sake bottle and cup',
		'🍷':'Wine glass',
		'🍸':'Cocktail glass',
		'🍹':'Tropical drink',
		'🍺':'Beer mug',
		'🍻':'Clinking beer mugs',
		'🍼':'Baby bottle',
		'🍽':'Fork and knife with plate',
		'🍾':'Bottle with popping cork',
		'🍿':'Popcorn',
		'🎀':'Ribbon',
		'🎁':'Wrapped present',
		'🎂':'Birthday cake',
		'🎃':'Jack-o-lantern',
		'🎄':'Christmas tree',
		'🎅':'Father christmas',
		'🎆':'Fireworks',
		'🎇':'Firework sparkler',
		'🎈':'Balloon',
		'🎉':'Party popper',
		'🎊':'Confetti ball',
		'🎋':'Tanabata tree',
		'🎌':'Crossed flags',
		'🎍':'Pine decoration',
		'🎎':'Japanese dolls',
		'🎏':'Carp streamer',
		'🎐':'Wind chime',
		'🎑':'Moon viewing ceremony',
		'🎒':'School satchel',
		'🎓':'Graduation cap',
		'🎖':'Military medal',
		'🎗':'Reminder ribbon',
		'🎙':'Studio microphone',
		'🎚':'Level slider',
		'🎛':'Control knobs',
		'🎞':'Film frames',
		'🎟':'Admission tickets',
		'🎠':'Carousel horse',
		'🎡':'Ferris wheel',
		'🎢':'Roller coaster',
		'🎣':'Fishing pole and fish',
		'🎤':'Microphone',
		'🎥':'Movie camera',
		'🎦':'Cinema',
		'🎧':'Headphone',
		'🎨':'Artist palette',
		'🎩':'Top hat',
		'🎪':'Circus tent',
		'🎫':'Ticket',
		'🎬':'Clapper board',
		'🎭':'Performing arts',
		'🎮':'Video game',
		'🎯':'Direct hit',
		'🎰':'Slot machine',
		'🎱':'Billiards',
		'🎲':'Game die',
		'🎳':'Bowling',
		'🎴':'Flower playing cards',
		'🎵':'Musical note',
		'🎶':'Multiple musical notes',
		'🎷':'Saxophone',
		'🎸':'Guitar',
		'🎹':'Musical keyboard',
		'🎺':'Trumpet',
		'🎻':'Violin',
		'🎼':'Musical score',
		'🎽':'Running shirt with sash',
		'🎾':'Tennis racquet and ball',
		'🎿':'Ski and ski boot',
		'🏀':'Basketball and hoop',
		'🏁':'Chequered flag',
		'🏂':'Snowboarder',
		'🏃':'Runner',
		'🏄':'Surfer',
		'🏅':'Sports medal',
		'🏆':'Trophy',
		'🏇':'Horse racing',
		'🏈':'American football',
		'🏉':'Rugby football',
		'🏊':'Swimmer',
		'🏋':'Weight lifter',
		'🏌':'Golfer',
		'🏍':'Racing motorcycle',
		'🏎':'Racing car',
		'🏏':'Cricket bat and ball',
		'🏐':'Volleyball',
		'🏑':'Field hockey stick and ball',
		'🏒':'Ice hockey stick and puck',
		'🏓':'Table tennis paddle and ball',
		'🏔':'Snow capped mountain',
		'🏕':'Camping',
		'🏖':'Beach with umbrella',
		'🏗':'Building construction',
		'🏘':'House buildings',
		'🏙':'Cityscape',
		'🏚':'Derelict house building',
		'🏛':'Classical building',
		'🏜':'Desert',
		'🏝':'Desert island',
		'🏞':'National park',
		'🏟':'Stadium',
		'🏠':'House building',
		'🏡':'House with garden',
		'🏢':'Office building',
		'🏣':'Japanese post office',
		'🏤':'European post office',
		'🏥':'Hospital',
		'🏦':'Bank',
		'🏧':'Automated teller machine',
		'🏨':'Hotel',
		'🏩':'Love hotel',
		'🏪':'Convenience store',
		'🏫':'School',
		'🏬':'Department store',
		'🏭':'Factory',
		'🏮':'Izakaya lantern',
		'🏯':'Japanese castle',
		'🏰':'European castle',
		'🏳':'Waving white flag',
		'🏴':'Waving black flag',
		'🏵':'Rosette',
		'🏷':'Label',
		'🏸':'Badminton racquet and shuttlecock',
		'🏹':'Bow and arrow',
		'🏺':'Amphora',
		'🏻':'Emoji modifier fitzpatrick type-1-2',
		'🏼':'Emoji modifier fitzpatrick type-3',
		'🏽':'Emoji modifier fitzpatrick type-4',
		'🏾':'Emoji modifier fitzpatrick type-5',
		'🏿':'Emoji modifier fitzpatrick type-6',
		'🐀':'Rat',
		'🐁':'Mouse',
		'🐂':'Ox',
		'🐃':'Water buffalo',
		'🐄':'Cow',
		'🐅':'Tiger',
		'🐆':'Leopard',
		'🐇':'Rabbit',
		'🐈':'Cat',
		'🐉':'Dragon',
		'🐊':'Crocodile',
		'🐋':'Whale',
		'🐌':'Snail',
		'🐍':'Snake',
		'🐎':'Horse',
		'🐏':'Ram',
		'🐐':'Goat',
		'🐑':'Sheep',
		'🐒':'Monkey',
		'🐓':'Rooster',
		'🐔':'Chicken',
		'🐕':'Dog',
		'🐖':'Pig',
		'🐗':'Boar',
		'🐘':'Elephant',
		'🐙':'Octopus',
		'🐚':'Spiral shell',
		'🐛':'Bug',
		'🐜':'Ant',
		'🐝':'Honeybee',
		'🐞':'Lady beetle',
		'🐟':'Fish',
		'🐠':'Tropical fish',
		'🐡':'Blowfish',
		'🐢':'Turtle',
		'🐣':'Hatching chick',
		'🐤':'Baby chick',
		'🐥':'Front-facing baby chick',
		'🐦':'Bird',
		'🐧':'Penguin',
		'🐨':'Koala',
		'🐩':'Poodle',
		'🐪':'Dromedary camel',
		'🐫':'Bactrian camel',
		'🐬':'Dolphin',
		'🐭':'Mouse face',
		'🐮':'Cow face',
		'🐯':'Tiger face',
		'🐰':'Rabbit face',
		'🐱':'Cat face',
		'🐲':'Dragon face',
		'🐳':'Spouting whale',
		'🐴':'Horse face',
		'🐵':'Monkey face',
		'🐶':'Dog face',
		'🐷':'Pig face',
		'🐸':'Frog face',
		'🐹':'Hamster face',
		'🐺':'Wolf face',
		'🐻':'Bear face',
		'🐼':'Panda face',
		'🐽':'Pig nose',
		'🐾':'Paw prints',
		'🐿':'Chipmunk',
		'👀':'Eyes',
		'👁':'Eye',
		'👂':'Ear',
		'👃':'Nose',
		'👄':'Mouth',
		'👅':'Tongue',
		'👆':'White up pointing backhand index',
		'👇':'White down pointing backhand index',
		'👈':'White left pointing backhand index',
		'👉':'White right pointing backhand index',
		'👊':'Fisted hand sign',
		'👋':'Waving hand sign',
		'👌':'Ok hand sign',
		'👍':'Thumbs up sign',
		'👎':'Thumbs down sign',
		'👏':'Clapping hands sign',
		'👐':'Open hands sign',
		'👑':'Crown',
		'👒':'Womans hat',
		'👓':'Eyeglasses',
		'👔':'Necktie',
		'👕':'T-shirt',
		'👖':'Jeans',
		'👗':'Dress',
		'👘':'Kimono',
		'👙':'Bikini',
		'👚':'Womans clothes',
		'👛':'Purse',
		'👜':'Handbag',
		'👝':'Pouch',
		'👞':'Mans shoe',
		'👟':'Athletic shoe',
		'👠':'High-heeled shoe',
		'👡':'Womans sandal',
		'👢':'Womans boots',
		'👣':'Footprints',
		'👤':'Bust in silhouette',
		'👥':'Busts in silhouette',
		'👦':'Boy',
		'👧':'Girl',
		'👨':'Man',
		'👩':'Woman',
		'👪':'Family',
		'👫':'Man and woman holding hands',
		'👬':'Two men holding hands',
		'👭':'Two women holding hands',
		'👮':'Police officer',
		'👯':'Woman with bunny ears',
		'👰':'Bride with veil',
		'👱':'Person with blond hair',
		'👲':'Man with gua pi mao',
		'👳':'Man with turban',
		'👴':'Older man',
		'👵':'Older woman',
		'👶':'Baby',
		'👷':'Construction worker',
		'👸':'Princess',
		'👹':'Japanese ogre',
		'👺':'Japanese goblin',
		'👻':'Ghost',
		'👼':'Baby angel',
		'👽':'Extraterrestrial alien',
		'👾':'Alien monster',
		'👿':'Imp',
		'💀':'Skull',
		'💁':'Information desk person',
		'💂':'Guardsman',
		'💃':'Dancer',
		'💄':'Lipstick',
		'💅':'Nail polish',
		'💆':'Face massage',
		'💇':'Haircut',
		'💈':'Barber pole',
		'💉':'Syringe',
		'💊':'Pill',
		'💋':'Kiss mark',
		'💌':'Love letter',
		'💍':'Ring',
		'💎':'Gem stone',
		'💏':'Kiss',
		'💐':'Bouquet',
		'💑':'Couple with heart',
		'💒':'Wedding',
		'💓':'Beating heart',
		'💔':'Broken heart',
		'💕':'Two hearts',
		'💖':'Sparkling heart',
		'💗':'Growing heart',
		'💘':'Heart with arrow',
		'💙':'Blue heart',
		'💚':'Green heart',
		'💛':'Yellow heart',
		'💜':'Purple heart',
		'💝':'Heart with ribbon',
		'💞':'Revolving hearts',
		'💟':'Heart decoration',
		'💠':'Diamond shape with a dot inside',
		'💡':'Electric light bulb',
		'💢':'Anger symbol',
		'💣':'Bomb',
		'💤':'Sleeping symbol',
		'💥':'Collision symbol',
		'💦':'Splashing sweat symbol',
		'💧':'Droplet',
		'💨':'Dash symbol',
		'💩':'Pile of poo',
		'💪':'Flexed biceps',
		'💫':'Dizzy symbol',
		'💬':'Speech balloon',
		'💭':'Thought balloon',
		'💮':'White flower',
		'💯':'Hundred points symbol',
		'💰':'Money bag',
		'💱':'Currency exchange',
		'💲':'Heavy dollar sign',
		'💳':'Credit card',
		'💴':'Banknote with yen sign',
		'💵':'Banknote with dollar sign',
		'💶':'Banknote with euro sign',
		'💷':'Banknote with pound sign',
		'💸':'Money with wings',
		'💹':'Chart with upwards trend and yen sign',
		'💺':'Seat',
		'💻':'Personal computer',
		'💼':'Briefcase',
		'💽':'Minidisc',
		'💾':'Floppy disk',
		'💿':'Optical disc',
		'📀':'Dvd',
		'📁':'File folder',
		'📂':'Open file folder',
		'📃':'Page with curl',
		'📄':'Page facing up',
		'📅':'Calendar',
		'📆':'Tear-off calendar',
		'📇':'Card index',
		'📈':'Chart with upwards trend',
		'📉':'Chart with downwards trend',
		'📊':'Bar chart',
		'📋':'Clipboard',
		'📌':'Pushpin',
		'📍':'Round pushpin',
		'📎':'Paperclip',
		'📏':'Straight ruler',
		'📐':'Triangular ruler',
		'📑':'Bookmark tabs',
		'📒':'Ledger',
		'📓':'Notebook',
		'📔':'Notebook with decorative cover',
		'📕':'Closed book',
		'📖':'Open book',
		'📗':'Green book',
		'📘':'Blue book',
		'📙':'Orange book',
		'📚':'Books',
		'📛':'Name badge',
		'📜':'Scroll',
		'📝':'Memo',
		'📞':'Telephone receiver',
		'📟':'Pager',
		'📠':'Fax machine',
		'📡':'Satellite antenna',
		'📢':'Public address loudspeaker',
		'📣':'Cheering megaphone',
		'📤':'Outbox tray',
		'📥':'Inbox tray',
		'📦':'Package',
		'📧':'E-mail symbol',
		'📨':'Incoming envelope',
		'📩':'Envelope with downwards arrow above',
		'📪':'Closed mailbox with lowered flag',
		'📫':'Closed mailbox with raised flag',
		'📬':'Open mailbox with raised flag',
		'📭':'Open mailbox with lowered flag',
		'📮':'Postbox',
		'📯':'Postal horn',
		'📰':'Newspaper',
		'📱':'Mobile phone',
		'📲':'Mobile phone with rightwards arrow at left',
		'📳':'Vibration mode',
		'📴':'Mobile phone off',
		'📵':'No mobile phones',
		'📶':'Antenna with bars',
		'📷':'Camera',
		'📸':'Camera with flash',
		'📹':'Video camera',
		'📺':'Television',
		'📻':'Radio',
		'📼':'Videocassette',
		'📽':'Film projector',
		'📿':'Prayer beads',
		'🔀':'Twisted rightwards arrows',
		'🔁':'Clockwise rightwards and leftwards open circle arrows',
		'🔂':'Clockwise rightwards and leftwards open circle arrows with circled one overlay',
		'🔃':'Clockwise downwards and upwards open circle arrows',
		'🔄':'Anticlockwise downwards and upwards open circle arrows',
		'🔅':'Low brightness symbol',
		'🔆':'High brightness symbol',
		'🔇':'Speaker with cancellation stroke',
		'🔈':'Speaker',
		'🔉':'Speaker with one sound wave',
		'🔊':'Speaker with three sound waves',
		'🔋':'Battery',
		'🔌':'Electric plug',
		'🔍':'Left-pointing magnifying glass',
		'🔎':'Right-pointing magnifying glass',
		'🔏':'Lock with ink pen',
		'🔐':'Closed lock with key',
		'🔑':'Key',
		'🔒':'Lock',
		'🔓':'Open lock',
		'🔔':'Bell',
		'🔕':'Bell with cancellation stroke',
		'🔖':'Bookmark',
		'🔗':'Link symbol',
		'🔘':'Radio button',
		'🔙':'Back with leftwards arrow above',
		'🔚':'End with leftwards arrow above',
		'🔛':'On with exclamation mark with left right arrow above',
		'🔜':'Soon with rightwards arrow above',
		'🔝':'Top with upwards arrow above',
		'🔞':'No one under eighteen symbol',
		'🔟':'Keycap ten',
		'🔠':'Input symbol for latin capital letters',
		'🔡':'Input symbol for latin small letters',
		'🔢':'Input symbol for numbers',
		'🔣':'Input symbol for symbols',
		'🔤':'Input symbol for latin letters',
		'🔥':'Fire',
		'🔦':'Electric torch',
		'🔧':'Wrench',
		'🔨':'Hammer',
		'🔩':'Nut and bolt',
		'🔪':'Hocho',
		'🔫':'Pistol',
		'🔬':'Microscope',
		'🔭':'Telescope',
		'🔮':'Crystal ball',
		'🔯':'Six pointed star with middle dot',
		'🔰':'Japanese symbol for beginner',
		'🔱':'Trident emblem',
		'🔲':'Black square button',
		'🔳':'White square button',
		'🔴':'Large red circle',
		'🔵':'Large blue circle',
		'🔶':'Large orange diamond',
		'🔷':'Large blue diamond',
		'🔸':'Small orange diamond',
		'🔹':'Small blue diamond',
		'🔺':'Up-pointing red triangle',
		'🔻':'Down-pointing red triangle',
		'🔼':'Up-pointing small red triangle',
		'🔽':'Down-pointing small red triangle',
		'🕇':'Heavy latin cross',
		'🕉':'Om symbol',
		'🕊':'Dove of peace',
		'🕋':'Kaaba',
		'🕌':'Mosque',
		'🕍':'Synagogue',
		'🕎':'Menorah with nine branches',
		'🕐':'Clock face one oclock',
		'🕑':'Clock face two oclock',
		'🕒':'Clock face three oclock',
		'🕓':'Clock face four oclock',
		'🕔':'Clock face five oclock',
		'🕕':'Clock face six oclock',
		'🕖':'Clock face seven oclock',
		'🕗':'Clock face eight oclock',
		'🕘':'Clock face nine oclock',
		'🕙':'Clock face ten oclock',
		'🕚':'Clock face eleven oclock',
		'🕛':'Clock face twelve oclock',
		'🕜':'Clock face one-thirty',
		'🕝':'Clock face two-thirty',
		'🕞':'Clock face three-thirty',
		'🕟':'Clock face four-thirty',
		'🕠':'Clock face five-thirty',
		'🕡':'Clock face six-thirty',
		'🕢':'Clock face seven-thirty',
		'🕣':'Clock face eight-thirty',
		'🕤':'Clock face nine-thirty',
		'🕥':'Clock face ten-thirty',
		'🕦':'Clock face eleven-thirty',
		'🕧':'Clock face twelve-thirty',
		'🕯':'Candle',
		'🕰':'Mantelpiece clock',
		'🕳':'Hole',
		'🕴':'Man in business suit levitating',
		'🕵':'Sleuth or spy',
		'🕶':'Dark sunglasses',
		'🕷':'Spider',
		'🕸':'Spider web',
		'🕹':'Joystick',
		'🖇':'Linked paperclips',
		'🖊':'Lower left ballpoint pen',
		'🖋':'Lower left fountain pen',
		'🖌':'Lower left paintbrush',
		'🖍':'Lower left crayon',
		'🖎':'Left writing hand',
		'🖐':'Raised hand with fingers splayed',
		'🖕':'Reversed hand with middle finger extended',
		'🖖':'Raised hand with part between middle and ring fingers',
		'🖥':'Desktop computer',
		'🖨':'Printer',
		'🖮':'Wired keyboard',
		'🖱':'Three button mouse',
		'🖲':'Trackball',
		'🖼':'Frame with picture',
		'🗂':'Card index dividers',
		'🗃':'Card file box',
		'🗄':'File cabinet',
		'🗑':'Wastebasket',
		'🗒':'Spiral note pad',
		'🗓':'Spiral calendar pad',
		'🗜':'Compression',
		'🗝':'Old key',
		'🗞':'Rolled-up newspaper',
		'🗡':'Dagger knife',
		'🗣':'Speaking head in silhouette',
		'🗯':'Right anger bubble',
		'🗳':'Ballot box with ballot',
		'🗺':'World map',
		'🗻':'Mount fuji',
		'🗼':'Tokyo tower',
		'🗽':'Statue of liberty',
		'🗾':'Silhouette of japan',
		'🗿':'Moyai',
		'😀':'Grinning face',
		'😁':'Grinning face with smiling eyes',
		'😂':'Face with tears of joy',
		'😃':'Smiling face with open mouth',
		'😄':'Smiling face with open mouth and smiling eyes',
		'😅':'Smiling face with open mouth and cold sweat',
		'😆':'Smiling face with open mouth and tightly-closed eyes',
		'😇':'Smiling face with halo',
		'😈':'Smiling face with horns',
		'😉':'Winking face',
		'😊':'Smiling face with smiling eyes',
		'😋':'Face savouring delicious food',
		'😌':'Relieved face',
		'😍':'Smiling face with heart-shaped eyes',
		'😎':'Smiling face with sunglasses',
		'😏':'Smirking face',
		'😐':'Neutral face',
		'😑':'Expressionless face',
		'😒':'Unamused face',
		'😓':'Face with cold sweat',
		'😔':'Pensive face',
		'😕':'Confused face',
		'😖':'Confounded face',
		'😗':'Kissing face',
		'😘':'Face throwing a kiss',
		'😙':'Kissing face with smiling eyes',
		'😚':'Kissing face with closed eyes',
		'😛':'Face with stuck-out tongue',
		'😜':'Face with stuck-out tongue and winking eye',
		'😝':'Face with stuck-out tongue and tightly-closed eyes',
		'😞':'Disappointed face',
		'😟':'Worried face',
		'😠':'Angry face',
		'😡':'Pouting face',
		'😢':'Crying face',
		'😣':'Persevering face',
		'😤':'Face with look of triumph',
		'😥':'Disappointed but relieved face',
		'😦':'Frowning face with open mouth',
		'😧':'Anguished face',
		'😨':'Fearful face',
		'😩':'Weary face',
		'😪':'Sleepy face',
		'😫':'Tired face',
		'😬':'Grimacing face',
		'😭':'Loudly crying face',
		'😮':'Face with open mouth',
		'😯':'Hushed face',
		'😰':'Face with open mouth and cold sweat',
		'😱':'Face screaming in fear',
		'😲':'Astonished face',
		'😳':'Flushed face',
		'😴':'Sleeping face',
		'😵':'Dizzy face',
		'😶':'Face without mouth',
		'😷':'Face with medical mask',
		'😸':'Grinning cat face with smiling eyes',
		'😹':'Cat face with tears of joy',
		'😺':'Smiling cat face with open mouth',
		'😻':'Smiling cat face with heart-shaped eyes',
		'😼':'Cat face with wry smile',
		'😽':'Kissing cat face with closed eyes',
		'😾':'Pouting cat face',
		'😿':'Crying cat face',
		'🙀':'Weary cat face',
		'🙁':'Slightly frowning face',
		'🙂':'Slightly smiling face',
		'🙃':'Upside-down face',
		'🙄':'Face with rolling eyes',
		'🙅':'Face with no good gesture',
		'🙆':'Face with ok gesture',
		'🙇':'Person bowing deeply',
		'🙈':'See-no-evil monkey',
		'🙉':'Hear-no-evil monkey',
		'🙊':'Speak-no-evil monkey',
		'🙋':'Happy person raising one hand',
		'🙌':'Person raising both hands in celebration',
		'🙍':'Person frowning',
		'🙎':'Person with pouting face',
		'🙏':'Person with folded hands',
		'🚀':'Rocket',
		'🚁':'Helicopter',
		'🚂':'Steam locomotive',
		'🚃':'Railway car',
		'🚄':'High-speed train',
		'🚅':'High-speed train with bullet nose',
		'🚆':'Train',
		'🚇':'Metro',
		'🚈':'Light rail',
		'🚉':'Station',
		'🚊':'Tram',
		'🚋':'Tram car',
		'🚌':'Bus',
		'🚍':'Oncoming bus',
		'🚎':'Trolleybus',
		'🚏':'Bus stop',
		'🚐':'Minibus',
		'🚑':'Ambulance',
		'🚒':'Fire engine',
		'🚓':'Police car',
		'🚔':'Oncoming police car',
		'🚕':'Taxi',
		'🚖':'Oncoming taxi',
		'🚗':'Automobile',
		'🚘':'Oncoming automobile',
		'🚙':'Recreational vehicle',
		'🚚':'Delivery truck',
		'🚛':'Articulated lorry',
		'🚜':'Tractor',
		'🚝':'Monorail',
		'🚞':'Mountain railway',
		'🚟':'Suspension railway',
		'🚠':'Mountain cableway',
		'🚡':'Aerial tramway',
		'🚢':'Ship',
		'🚣':'Rowboat',
		'🚤':'Speedboat',
		'🚥':'Horizontal traffic light',
		'🚦':'Vertical traffic light',
		'🚧':'Construction sign',
		'🚨':'Police cars revolving light',
		'🚩':'Triangular flag on post',
		'🚪':'Door',
		'🚫':'No entry sign',
		'🚬':'Smoking symbol',
		'🚭':'No smoking symbol',
		'🚮':'Put litter in its place symbol',
		'🚯':'Do not litter symbol',
		'🚰':'Potable water symbol',
		'🚱':'Non-potable water symbol',
		'🚲':'Bicycle',
		'🚳':'No bicycles',
		'🚴':'Bicyclist',
		'🚵':'Mountain bicyclist',
		'🚶':'Pedestrian',
		'🚷':'No pedestrians',
		'🚸':'Children crossing',
		'🚹':'Mens symbol',
		'🚺':'Womens symbol',
		'🚻':'Restroom',
		'🚼':'Baby symbol',
		'🚽':'Toilet',
		'🚾':'Water closet',
		'🚿':'Shower',
		'🛀':'Bath',
		'🛁':'Bathtub',
		'🛂':'Passport control',
		'🛃':'Customs',
		'🛄':'Baggage claim',
		'🛅':'Left luggage',
		'🛋':'Couch and lamp',
		'🛌':'Sleeping accommodation',
		'🛍':'Shopping bags',
		'🛎':'Bellhop bell',
		'🛏':'Bed',
		'🛐':'Place of worship',
		'🛠':'Hammer and wrench',
		'🛡':'Shield',
		'🛢':'Oil drum',
		'🛣':'Motorway',
		'🛤':'Railway track',
		'🛥':'Motor boat',
		'🛩':'Small airplane',
		'🛫':'Airplane departure',
		'🛬':'Airplane arriving',
		'🛰':'Satellite',
		'🛳':'Passenger ship',
		'🤐':'Zipper-mouth face',
		'🤑':'Money-mouth face',
		'🤒':'Face with thermometer',
		'🤓':'Nerd face',
		'🤔':'Thinking face',
		'🤕':'Face with head-bandage',
		'🤖':'Robot face',
		'🤗':'Hugging face',
		'🤘':'Sign of the horns',
		'🦀':'Crab',
		'🦁':'Lion face',
		'🦂':'Scorpion',
		'🦃':'Turkey',
		'🦄':'Unicorn face',
		'🧀':'Cheese wedge'
	},

	replace: function(node)
	{
		if (this.use_native) {
			// http://caniemoji.com/
			var ua = navigator.userAgent, m = ua.match(/Android\s([0-9\.]*)/);
			if (ua.match(/iPhone|iPod|iPad/i) || (m && 4.4 <= parseFloat(m[1]))) { return; }
		}

		// First walk through each textNode and place matching nodes in a list
		var walker = document.createTreeWalker(node || document.body, NodeFilter.SHOW_TEXT, null, false), n, nodes = [];
		while (n = walker.nextNode()) {
			// Skip if this textNode is already a replaced Emoji or Textarea
			if (!n.parentNode.hasClass('emoji') && 'textarea' !== n.parentNode.lowerName()) {
				var v = ' ' + n.textContent, e = v.match(this.regex);
				if (e) {
					var t = v.split(this.regex);
					t[0] = t[0].substr(1);
					nodes.push({
						node: n,
						text: t,
						emoji: e
					});
				}
			}
		}

		// Now process all emoji's
		nodes.forEach(function(o){
			var emojis = Poodle.Emoji.emojis,
				n = o.node,
				p = n.parentNode,
				s = n.nextSibling,
				t = o.text,
				e = o.emoji,
				i = 0;
			n.textContent = '';
			for (; i<t.length; ++i) {
				n.textContent += t[i];
				if (e[i]) {
					if (emojis[e[i]] /*&& !Poodle.Emoji.nativeSupport(e[i])*/) {
						p.insertBefore(Poodle.$C('span', {
							title: emojis[e[i]],
//							'class': 'emoji emoji-' + ((e[i].charCodeAt(0) - 0xD800) * 0x400 + e[i].charCodeAt(1) - 0xDC00 + 0x10000).toString(16).toUpperCase(),
							'class': 'emoji emoji-' + (((e[i].charCodeAt(0) & 0x3FF) << 10) + (e[i].charCodeAt(1) & 0x3FF) + 0x10000).toString(16).toUpperCase(),
							textContent: e[i]
						}), s);
						n = p.insertBefore(document.createTextNode(''), s);
					} else {
						n.textContent += e[i];
					}
				}
			}
		});
	},

	// Detects if browser has native support for the given emoji
	nativeSupport: function(emoji)
	{
		var n = Poodle.$C('canvas'), c = n.getContext ? n.getContext('2d') : null;
		if (c && is_function(c.fillText)) {
			c.textBaseline = 'top';
			c.font = '32px Arial';
			c.fillText(emoji || '\ud83d\ude03', 0, 0);
			return c.getImageData(16, 16, 1, 1).data[0] !== 0;
		}
		return false;
	}

};

Poodle.onDOMReady(function(){Poodle.Emoji.replace();});
